---
- name: Install Desktop Apps | Update APT and install apps.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - xserver-xorg
    - raspberrypi-ui-mods

- name: Schedule nightly reboot
  ansible.builtin.cron:
    name: "Nightly Reboot"
    weekday: "*"
    minute: "0"
    hour: "02"
    user: root
    job: "shutdown -r now"
    cron_file: autoreboot
