---
- name: Install Desktop Apps | Update APT and install apps.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - xserver-xorg
    - raspberrypi-ui-mods
